/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculator;

/**
 *
 * @author Mus'ap Aşkın
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorJFrame
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jTextField1 = new javax.swing.JTextField();
        BTN7 = new javax.swing.JToggleButton();
        BTN4 = new javax.swing.JToggleButton();
        BTNClear = new javax.swing.JToggleButton();
        BTN9 = new javax.swing.JToggleButton();
        BTNDivide = new javax.swing.JToggleButton();
        BTN1 = new javax.swing.JToggleButton();
        BTN5 = new javax.swing.JToggleButton();
        BTN6 = new javax.swing.JToggleButton();
        BTN3 = new javax.swing.JToggleButton();
        BTN0 = new javax.swing.JToggleButton();
        BTN2 = new javax.swing.JToggleButton();
        BTNPlus = new javax.swing.JToggleButton();
        BTNCalculate = new javax.swing.JToggleButton();
        BTN00 = new javax.swing.JToggleButton();
        BTN8 = new javax.swing.JToggleButton();
        BTNMinus = new javax.swing.JToggleButton();
        BTNMultiplication = new javax.swing.JToggleButton();

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextPane1.setName("jTextPane1"); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTextPane2.setName("jTextPane2"); // NOI18N
        jScrollPane2.setViewportView(jTextPane2);

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jTextPane3.setName("jTextPane3"); // NOI18N
        jScrollPane3.setViewportView(jTextPane3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaCalculatorApp");
        setBackground(new java.awt.Color(187, 187, 187));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(850, 300));
        setName("Form"); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setName("jTextField1"); // NOI18N

        BTN7.setText("7");
        BTN7.setName("BTN7"); // NOI18N
        BTN7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN7MouseClicked(evt);
            }
        });

        BTN4.setText("4");
        BTN4.setName("BTN4"); // NOI18N
        BTN4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN4MouseClicked(evt);
            }
        });

        BTNClear.setBackground(new java.awt.Color(153, 0, 0));
        BTNClear.setForeground(new java.awt.Color(204, 204, 204));
        BTNClear.setText("C");
        BTNClear.setName("BTNClear"); // NOI18N
        BTNClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNClearMouseClicked(evt);
            }
        });

        BTN9.setText("9");
        BTN9.setName("BTN9"); // NOI18N
        BTN9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN9MouseClicked(evt);
            }
        });

        BTNDivide.setBackground(new java.awt.Color(0, 0, 0));
        BTNDivide.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTNDivide.setForeground(new java.awt.Color(204, 204, 204));
        BTNDivide.setText("÷");
        BTNDivide.setName("BTNDivide"); // NOI18N
        BTNDivide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNDivideMouseClicked(evt);
            }
        });

        BTN1.setText("1");
        BTN1.setName("BTN1"); // NOI18N
        BTN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN1MouseClicked(evt);
            }
        });

        BTN5.setText("5");
        BTN5.setName("BTN5"); // NOI18N
        BTN5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN5MouseClicked(evt);
            }
        });

        BTN6.setText("6");
        BTN6.setName("BTN6"); // NOI18N
        BTN6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN6MouseClicked(evt);
            }
        });

        BTN3.setText("3");
        BTN3.setName("BTN3"); // NOI18N
        BTN3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN3MouseClicked(evt);
            }
        });

        BTN0.setText("0");
        BTN0.setName("BTN0"); // NOI18N
        BTN0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN0MouseClicked(evt);
            }
        });

        BTN2.setText("2");
        BTN2.setName("BTN2"); // NOI18N
        BTN2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN2MouseClicked(evt);
            }
        });

        BTNPlus.setBackground(new java.awt.Color(0, 0, 0));
        BTNPlus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTNPlus.setForeground(new java.awt.Color(204, 204, 204));
        BTNPlus.setText("+");
        BTNPlus.setName("BTNPlus"); // NOI18N
        BTNPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNPlusMouseClicked(evt);
            }
        });

        BTNCalculate.setBackground(new java.awt.Color(0, 51, 102));
        BTNCalculate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTNCalculate.setForeground(new java.awt.Color(204, 204, 204));
        BTNCalculate.setText("=");
        BTNCalculate.setName("BTNCalculate"); // NOI18N
        BTNCalculate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNCalculateMouseClicked(evt);
            }
        });

        BTN00.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BTN00.setText(".");
        BTN00.setName("BTN00"); // NOI18N
        BTN00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN00MouseClicked(evt);
            }
        });

        BTN8.setText("8");
        BTN8.setName("BTN8"); // NOI18N
        BTN8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN8MouseClicked(evt);
            }
        });

        BTNMinus.setBackground(new java.awt.Color(0, 0, 0));
        BTNMinus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTNMinus.setForeground(new java.awt.Color(204, 204, 204));
        BTNMinus.setText("-");
        BTNMinus.setName("BTNMinus"); // NOI18N
        BTNMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNMinusMouseClicked(evt);
            }
        });

        BTNMultiplication.setBackground(new java.awt.Color(0, 0, 0));
        BTNMultiplication.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTNMultiplication.setForeground(new java.awt.Color(204, 204, 204));
        BTNMultiplication.setText("*");
        BTNMultiplication.setName("BTNMultiplication"); // NOI18N
        BTNMultiplication.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNMultiplicationMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTN2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTN3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTN0, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTN00, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTNClear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTN7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTN8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTN9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BTN4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTN5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTN6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTN7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTN4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BTNPlus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTN0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN00, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNDivideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNDivideMouseClicked
        if (!(jTextField1.getText().isEmpty())) {
            operator = "/";
            answer = Double.parseDouble(jTextField1.getText());
            jTextField1.setText("");
        }
    }//GEN-LAST:event_BTNDivideMouseClicked

    private void BTN0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN0MouseClicked
        if (jTextField1.getText().isEmpty()) {
            jTextField1.setText(BTN0.getText());
        } else {

            jTextField1.setText(jTextField1.getText() + BTN0.getText());
        }
    }//GEN-LAST:event_BTN0MouseClicked

    private void BTN1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN1MouseClicked
        if (jTextField1.getText().isEmpty()) {
            jTextField1.setText(BTN1.getText());
        } else {
            jTextField1.setText(jTextField1.getText() + BTN1.getText());
        }
    }//GEN-LAST:event_BTN1MouseClicked

    private void BTN2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN2MouseClicked
        if (jTextField1.getText().isEmpty()) {
            jTextField1.setText(BTN2.getText());
        } else {
            jTextField1.setText(jTextField1.getText() + BTN2.getText());
        }
    }//GEN-LAST:event_BTN2MouseClicked

    private void BTN3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN3MouseClicked
        if (jTextField1.getText().isEmpty()) {
            jTextField1.setText(BTN3.getText());
        } else {
            jTextField1.setText(jTextField1.getText() + BTN3.getText());
        }
    }//GEN-LAST:event_BTN3MouseClicked

    private void BTN5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN5MouseClicked
        if (jTextField1.getText().isEmpty()) {
            jTextField1.setText(BTN5.getText());
        } else {
            jTextField1.setText(jTextField1.getText() + BTN5.getText());
        }
    }//GEN-LAST:event_BTN5MouseClicked

    private void BTN4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN4MouseClicked
        if (jTextField1.getText().isEmpty()) {
            jTextField1.setText(BTN4.getText());
        } else {
            jTextField1.setText(jTextField1.getText() + BTN4.getText());
        }
    }//GEN-LAST:event_BTN4MouseClicked

    private void BTN6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN6MouseClicked
        if (jTextField1.getText().isEmpty()) {
            jTextField1.setText(BTN6.getText());
        } else {
            jTextField1.setText(jTextField1.getText() + BTN6.getText());
        }
    }//GEN-LAST:event_BTN6MouseClicked

    private void BTN7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN7MouseClicked
        if (jTextField1.getText().isEmpty()) {
            jTextField1.setText(BTN7.getText());
        } else {
            jTextField1.setText(jTextField1.getText() + BTN7.getText());
        }
    }//GEN-LAST:event_BTN7MouseClicked

    private void BTN8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN8MouseClicked
        if (jTextField1.getText().isEmpty()) {
            jTextField1.setText(BTN8.getText());
        } else {
            jTextField1.setText(jTextField1.getText() + BTN8.getText());
        }
    }//GEN-LAST:event_BTN8MouseClicked

    private void BTN9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN9MouseClicked
        if (jTextField1.getText().isEmpty()) {
            jTextField1.setText(BTN9.getText());
        } else {
            jTextField1.setText(jTextField1.getText() + BTN9.getText());
        }
    }//GEN-LAST:event_BTN9MouseClicked

    private void BTNClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNClearMouseClicked
        jTextField1.setText("");
        answer = 0;
    }//GEN-LAST:event_BTNClearMouseClicked

    private void BTNPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNPlusMouseClicked
        if (!(jTextField1.getText().isEmpty())) {
            operator = "+";
            answer = Double.parseDouble(jTextField1.getText());
            jTextField1.setText("");
        }
    }//GEN-LAST:event_BTNPlusMouseClicked

    private void BTNCalculateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNCalculateMouseClicked
        if (operator == "+") {
            answer += Double.parseDouble(jTextField1.getText());
        } else if (operator == "-") {
            answer -= Double.parseDouble(jTextField1.getText());
        } else if (operator == "*") {
            answer *= Double.parseDouble(jTextField1.getText());
        } else if (operator == "/") {
            answer /= Double.parseDouble(jTextField1.getText());
        } else {
            answer = Double.parseDouble(jTextField1.getText());
        }
        operator = "";
        jTextField1.setText(Double.toString(answer));
    }//GEN-LAST:event_BTNCalculateMouseClicked

    private void BTNMultiplicationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNMultiplicationMouseClicked
        if (!(jTextField1.getText().isEmpty())) {
            operator = "*";
            answer = Double.parseDouble(jTextField1.getText());
            jTextField1.setText("");
        }
    }//GEN-LAST:event_BTNMultiplicationMouseClicked

    private void BTNMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNMinusMouseClicked
        if (!(jTextField1.getText().isEmpty())) {
            operator = "-";
            answer = Double.parseDouble(jTextField1.getText());
            jTextField1.setText("");
        }
    }//GEN-LAST:event_BTNMinusMouseClicked

    private void BTN00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN00MouseClicked
        if (jTextField1.getText().isEmpty()) {
            jTextField1.setText(BTN00.getText());
        } else {
            jTextField1.setText(jTextField1.getText() + BTN00.getText());
        }
    }//GEN-LAST:event_BTN00MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }
    double answer;
    String operator;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BTN0;
    private javax.swing.JToggleButton BTN00;
    private javax.swing.JToggleButton BTN1;
    private javax.swing.JToggleButton BTN2;
    private javax.swing.JToggleButton BTN3;
    private javax.swing.JToggleButton BTN4;
    private javax.swing.JToggleButton BTN5;
    private javax.swing.JToggleButton BTN6;
    private javax.swing.JToggleButton BTN7;
    private javax.swing.JToggleButton BTN8;
    private javax.swing.JToggleButton BTN9;
    private javax.swing.JToggleButton BTNCalculate;
    private javax.swing.JToggleButton BTNClear;
    private javax.swing.JToggleButton BTNDivide;
    private javax.swing.JToggleButton BTNMinus;
    private javax.swing.JToggleButton BTNMultiplication;
    private javax.swing.JToggleButton BTNPlus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    // End of variables declaration//GEN-END:variables
}
